"""add_subscription_fields

Revision ID: 3082b97550cb
Revises: 8aa2b307a70a
Create Date: 2025-12-24 16:47:19.450800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3082b97550cb'
down_revision: Union[str, Sequence[str], None] = '8aa2b307a70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entries', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_log_entries_org_id'), 'log_entries', ['org_id'], unique=False)
    op.create_foreign_key(None, 'log_entries', 'organizations', ['org_id'], ['id'])
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('subscription_id', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.add_column('surveys', sa.Column('org_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_surveys_user_id'), table_name='surveys')
    op.create_index(op.f('ix_surveys_org_id'), 'surveys', ['org_id'], unique=False)
    op.create_foreign_key(None, 'surveys', 'organizations', ['org_id'], ['id'])
    op.add_column('users', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_column('users', 'org_id')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_index(op.f('ix_surveys_org_id'), table_name='surveys')
    op.create_index(op.f('ix_surveys_user_id'), 'surveys', ['user_id'], unique=False)
    op.drop_column('surveys', 'org_id')
    op.drop_column('organizations', 'current_period_end')
    op.drop_column('organizations', 'subscription_id')
    op.drop_column('organizations', 'subscription_status')
    op.drop_constraint(None, 'log_entries', type_='foreignkey')
    op.drop_index(op.f('ix_log_entries_org_id'), table_name='log_entries')
    op.drop_column('log_entries', 'org_id')
    # ### end Alembic commands ###
