"""Add denominations and scripture_sets tables

Revision ID: 5a3d1d8d8492
Revises: 1a69f2de6106
Create Date: 2025-12-31 01:21:22.676227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a3d1d8d8492'
down_revision: Union[str, Sequence[str], None] = '1a69f2de6106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('denomination_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_organizations_denomination_id'), 'organizations', ['denomination_id'], unique=False)
    op.create_foreign_key(None, 'organizations', 'denominations', ['denomination_id'], ['id'])
    op.drop_column('organizations', 'current_period_end')
    op.drop_column('organizations', 'subscription_id')
    op.drop_column('organizations', 'subscription_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('subscription_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_index(op.f('ix_organizations_denomination_id'), table_name='organizations')
    op.drop_column('organizations', 'denomination_id')
    # ### end Alembic commands ###
