"""add_request_id_to_logs

Revision ID: 5a42da649428
Revises: 27eb8521f48c
Create Date: 2025-12-21 00:44:05.417537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a42da649428'
down_revision: Union[str, Sequence[str], None] = '27eb8521f48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entries', sa.Column('request_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_log_entries_request_id'), 'log_entries', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entries_request_id'), table_name='log_entries')
    op.drop_column('log_entries', 'request_id')
    # ### end Alembic commands ###
