"""Add is_demo to Organization

Revision ID: 748d45abbe8a
Revises: 3082b97550cb
Create Date: 2025-12-25 23:30:53.721306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '748d45abbe8a'
down_revision: Union[str, Sequence[str], None] = '3082b97550cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('organizations', 'branding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('surveys', sa.Column('assessment_version', sa.String(length=20), nullable=False, server_default=sa.text("'1.0'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'assessment_version')
    op.add_column('organizations', sa.Column('current_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('subscription_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('organizations', 'branding',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('organizations', 'is_demo')
    # ### end Alembic commands ###
