"""add_index_to_surveys_user_id

Revision ID: 8aa2b307a70a
Revises: e23de9ac059d
Create Date: 2025-12-21 15:00:06.512477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa2b307a70a'
down_revision: Union[str, Sequence[str], None] = 'e23de9ac059d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_surveys_user_id'), 'surveys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surveys_user_id'), table_name='surveys')
    # ### end Alembic commands ###
